#!/usr/bin/env python

import sys, time
from lib.SmartMessageDaemon import SmartMessageDaemon

if __name__ == "__main__":
	daemon = SmartMessageDaemon('/var/lock/smartMessage.pid')
	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			daemon.start()
		elif 'stop' == sys.argv[1]:
			daemon.stop()
		elif 'restart' == sys.argv[1]:
			daemon.restart()
		elif 'status' == sys.argv[1]:
			print "Not implemented yet - todo"
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "Usage: %s start|stop|restart" % sys.argv[0]
		sys.exit(2)
